version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: '12:00'
    open-pull-requests-limit: 4

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: '12:00'
    open-pull-requests-limit: 4
